### ISSUE TITLE
Throws error when shadowing inherited getter

### ISSUE THREAD

**Issue by Zirro** [jsdom/webidl2js#113]
The following combination of IDLs currently result in a `duplicated named getter`-error:

```webidl
[Exposed=Window, LegacyUnenumerableNamedProperties]
interface HTMLCollection {
  readonly attribute unsigned long length;
  [WebIDL2JSValueAsUnsupported=null] getter Element? item(unsigned long index);
  [WebIDL2JSValueAsUnsupported=null] getter Element? namedItem(DOMString name);
};

[Exposed=Window]
interface HTMLFormControlsCollection : HTMLCollection {
  // inherits length and item()
  [WebIDL2JSValueAsUnsupported=null] getter (RadioNodeList or Element)? namedItem(DOMString name); // shadows inherited namedItem()
};
```

`Error: Invalid getter "namedItem" on interface HTMLFormControlsCollection (defined in HTMLCollection): duplicated named getter`

The `namedItem()` on `HTMLFormControlsCollection` shadows the one from `HTMLCollection`. Going by the spec, it seems like this should be possible.

**Comment by TimothyGu** [comment]
The Web IDL spec [says](https://heycam.github.io/webidl/#idl-special-operations):

> If an object implements more than one [interface](https://heycam.github.io/webidl/#dfn-interface) that defines a given special operation, then it is undefined which (if any) special operation is invoked for that operation.

That was my original reason for disallowing shadowing.

**Comment by domenic** [comment]
Moved to https://github.com/heycam/webidl/issues/833

**Comment by UndefinedBehaviour** [comment]
I understand the root of the issue is in the webidl spec, but I think it would make sense to implement what browsers do (I checked Chrome and Firefox) i.e. use the definition in the most derived class.
This would allow to implement HTMLFormControlsCollection (and do away with one [TODO](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLFormElement-impl.js#L64) in the code), which in turn would allow to implement RadioNodeList (and close https://github.com/jsdom/jsdom/issues/2600).
What do you think?

**Comment by domenic** [comment]
Yeah, a PR to fix this with a link to the relevant spec issue would be welcome.
