### ISSUE TITLE
Handling overloads

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#29]
Would be nice if given

```
void append(USVString name, USVString value);
void append(USVString name, Blob value, optional USVString filename);
```

I could write `append1()` and `append2()` in the impl class and have it call to the correct one.

**Comment by TimothyGu** [comment]
Using a numeric index can be very volatile, and also doesn't play well when you want to call the impl method from another impl class. Also, in general the [overload resolution algorithm](https://heycam.github.io/webidl/#dfn-overload-resolution-algorithm) specifies runtime semantics, and is pretty difficult to translate to static semantics. E.g. for

```
void append(USVString name, Node arg1, Blob arg2);
void append(USVString name, Blob arg1, Node arg2);
void append(USVString name, Error arg1);
```

webidl2js must ideally generate something like

```js
if (Blob.is(args[1])) {
  args[1] = unwrap(args[1]);
  if (Node.is(args[2])) {
    args[2] = unwrap(args[2]);
  } else {
    throw new TypeError("Argument is not a Node");
  }
} else if (Node.is(args[1])) {
  args[1] = unwrap(args[1]);
  if (Blob.is(args[2])) {
    args[2] = unwrap(args[2]);
  } else {
    throw new TypeError("Argument is not a Blob");
  }
} else if (args[1] instanceof Error) {
  args[1] = conversions["Error"](args[1]); // or omitted
} else {
  throw new TypeError("Argument is not a Blob or a Node");
}
```

which IMO is a pretty big feat to do statically.

Alternatively, we could merge the IDL above into

```
void append(USVString name, (Node or Blob or Error) arg1, (Blob or Node) arg2);
```

which is a lot easier to generate:

```js
// Group all interface types together when generating (step 4)
// https://heycam.github.io/webidl/#es-to-union

// arg1
if (Node.is(args[1]) || Blob.is(args[1])) { // step 4
  args[1] = unwrap(args[1]);
} else if (args[1] instanceof Error) { // step 6
  args[1] = conversions["Error"](args[1]); // or omitted
} else { // step 17
  throw new Error("Argument is not Node, Blob or Error");
}

// arg2
if (Node.is(args[2]) || Blob.is(args[2])) { // step 4
  args[2] = unwrap(args[2]);
} else {
  throw new Error("Argument is not Node or Blob");
}
```

The flip-flop error checking logic can be implemented easily enough in the impl class (and this error checking is good to have for the cases when other impl's call this method themselves anyway):

```js
if (Blob.isImpl(args[1])) {
  if (!Node.isImpl(args[2])) {
    throw new TypeError("arg2 is not a Node");
  }

  // do things with [Blob, Node]
} else if (Node.isImpl(args[1])) {
  if (!Blob.isImpl(args[2])) {
    throw new TypeError("arg2 is not a Blob");
  }

  // do things with [Node, Blob]
} else {
  // do things with [Error]
}
```

**Comment by Sebmaster** [comment]
I personally always liked option 2 better - keeps more in line with how JS actually works.

**Comment by domenic** [comment]
My understanding is that overloads cannot, in general, be replaced with unions; there are cases that do not map back and forth.

I also thought that matching how C++/Rust implementations work would be a virtue, and those all use the overload resolution algorithm at runtime (in the generated binding code) to determine which of the C++ overloads to call. So I am still leaning toward the first approach.

**Comment by TimothyGu** [comment]
> My understanding is that overloads cannot, in general, be replaced with unions; there are cases that do not map back and forth.

Can you provide examples for such cases?

**Comment by domenic** [comment]
Sure. In general anything that varies on arity will have that problem. For example:

```webidl
interface A {
  void f();
  long f(double arg);
}
```

Real-world examples are `XMLHttpRequest`'s `open()`, and `FormData`'s `set()` and `append()`.

**Comment by TimothyGu** [comment]
@domenic, what I had on my mind for those cases is to add `optional` annotations, like

----

```webidl
void a();
long a(double arg);
Blob a(Blob arg, Blob arg2);

void b(USVString arg, USVString arg2);
void b(DOMString arg, Blob arg2);
```

to

```webidl
// return type use the generic tryWrapperForImpl handling
// just make sure the impl handles return type correctly
Blob a(optional (double or Blob) arg, optional Blob arg2);

// USVString and DOMString are not distinguishable; choose the less intrusive
void b(DOMString arg, (USVString or Blob) arg2);
```

----

What I am worried about is potential differences in the semantics of choosing a Web IDL type given a ES value between that of union type and of overloading. If such differences do exist, it's possible this solution won't work at all; but otherwise I think it's quite doable.

**Comment by domenic** [comment]
I am trying to gin up some examples, as I am sure I have seen them in the past, but maybe @bzbarsky can do so quicker. @bzbarsky, any canonical examples of where overloading cannot be emulated by a combination of optional and union types?

**Comment by domenic** [comment]
I think this might be a counterexample:

```webidl
interface A1 {
  void f();
  void f(double arg1, double arg2);
}

interface A2 {
  void f();
  void f(double arg1, optional double arg2);
}

interface A3 {
  void f(optional double arg1, optional double arg2);
}
```

Consider the three calls `a.f()`, `a.f(1)`, and `a.f(1, 2)`.

For `A1`, `a.f()` and `a.f(1)` will trigger the first overload, and `a.f(1, 2)` will trigger the second.

For `A2`, `a.f()` will trigger the first overload, and `a.f(1)` and `a.f(1, 2)` will trigger the second.

For `A3`, how do you know what `a.f(2)` should do? That is, how do you know whether it was originally trying to emulate `A1` or `A2`?

**Comment by domenic** [comment]
I guess all my above example shows is that optional is less expressive than overloads, so you'd need additional prose. That doesn't really invalidate your point, except by some slippery slope argument of the form that yes, we could get rid of overloading if every method just ended up duplicating the overload resolution algorithm inside its prose.

**Comment by bzbarsky** [comment]
So on a spec level... at the moment there are certainly behaviors you can do with overloads that you can't do with unions and optional arguments per se.  On the other hand, those behaviors may be bad API.  For example, consider this API:

    interface A {
      void foo();
      void foo(Node? arg);
    }

where `foo()` and `foo(null)` are defined to have different behavior.  Now consider script that does:

    foo(undefined);

The way the effective overload set construction algorithm and overload resolution algorithm are currently written, I believe this will select the second overload and invoke it with a null `Node?`, giving it the behavior of `foo(null)`.  Specifically, we will land in effective overload set construction (argh, why is this not linkable? ) with _N_ = 1.  _maxarg_ is also 1.  So we end up with an overload of length 0 and an overload of length 1.  The overload of length 1 is selected, has a non-optional argument, `undefined` is converted to that argument, and ends up as a null `Node?`.

On the other hand, rewriting this as:

    interface A {
      void foo(optional Node? arg);
    }

would make `foo()` and `foo(undefined)` have identical behavior, both different from `foo(null)`.  That's because now the length-1 overload has an _optional_ argument, and `undefined` being passed leads to the "missing" value being appended to the list in the `foo(undefined)` case.  As for the `foo()` case, step 15 of the overload resolution algorithm pads out the value list with "missing" for trailing optional arguments, so you end up with the same thing: the _values_ list in the return value of the overload resolution algorithm has length 1 and contains a single "missing" value.

You _can_, however write things this way:

    interface A {
      void foo(Node?... arg);
    }

and that will let you distinguish `foo()` from `foo(undefined)`: the former will gives a length-0 _values_ list, and the latter a length-1 _values_, returned from the overload resolution algorithm.  I'm assuming here that _values_ knows its own length, of course.  ;)

Obviously you can express any API as:

    void foo(any... arg);

and prose...

Anyway, in practical terms here are some existing interfaces in the web platform which use overloads and have different semantics than the equivalent thing with optional args would have; all have the property that some of the "optional" arguments can be validly coerced from `undefined`:

http://dev.w3.org/csswg/css3-conditional/ has:

    partial interface CSS {
      static boolean supports(DOMString property, DOMString value);
      static boolean supports(DOMString conditionText);
    };

https://html.spec.whatwg.org/multipage/scripting.html#canvasdrawimage has:

    void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy);
    void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh);
    void drawImage(CanvasImageSource image, unrestricted double sx, unrestricted double sy, unrestricted double sw, unrestricted double sh, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh);

Or here's a but from https://html.spec.whatwg.org/multipage/scripting.html#canvasdrawpath which would throw for `stroke(undefined)` as currently specced, but not when doing optionals (which may be OK):

    void stroke();
    void stroke(Path2D path);

**Comment by bzbarsky** [comment]
Note that I did NOT look through all overload uses in the web platform to see whether any others would have other problems converting to unions and optionals.

**Comment by domenic** [comment]
Thanks so much @bzbarsky! Would you say that most of the potential differences come from the treatment of `undefined`, or are there other issues you could think of? In general the fact that https://heycam.github.io/webidl/#es-union is a separate algorithm from the "compute an effective overload set" algorithm/the distinguishability table seems to imply that there could be other mismatches, perhaps even by accident...

**Comment by bzbarsky** [comment]
> I also thought that matching how C++/Rust implementations work would be a virtue

One other note: Rust and C++ work somewhat differently here, because Rust doesn't have method overloading.  So iirc the Rust bindings have to synthesize different names for the different overloads.

> Would you say that most of the potential differences come from the treatment of `undefined`

In terms of observable behavior, I think so.  I just recalled the case where this really really matters, actually: XHR's `open` method, for which passing `undefined` for the third arg means "sync XHR" but passing only two args means "async XHR", and the web depends on this iirc.

But you're right.  The fact that unions are separate from overload resolution does mean that you can get other interesting mismatches if you carefully contrive your API, even though we tried hard to avoid such mismatches for simple cases of various sorts.  In particular, the aim is that union conversion _exactly_ matches that of the _distinguishing_ argument for overload resolution.  But that tells you nothing about the _other_ arguments.  For example, consider this:

    void foo(InterfaceA arg1, DOMString arg2);
    void foo(InterfaceB arg2, long arg2);

vs

    void foo((InterfaceA or InterfaceB) arg1, (DOMString or long) arg2);

Now consider this call:

    foo(interfaceArg, { valueOf: () => console.log("long"), toString: () => console.log("DOMString") }) ;

If I read things correctly, the union version will always log "DOMString" because https://heycam.github.io/webidl/#es-to-union has the check for a string type in step 14 and the check for a numeric type in step 15.  But the overload version will log "long" if passed an instance of interfaceA for the first arg and "DOMString" if passed an instance of interfaceB.

Now you _could_ make this work in the union version by making the second type "any" and inspecting the type of the first arg before committing to a conversion for the second arg, etc...  It's just not the natural way to write this API as unions.  But arguably, there _is_ no natural way to write this API as unions, really.

I don't actually have a good feel for whether cases like this are more or less common than case where `undefined` is an issue.  :(

**Comment by domenic** [comment]
Great example, thank you! I feel equipped to write that informative section in Web IDL now, and also hopefully to settle this thread (in webidl2js) in favor of actually supporting overloads instead of trying to shoehorn them into unions/optional.

It's interesting to hear Rust, like JavaScript, doesn't support overloading; we'll also need to synthesize method names in that way in webidl2js. I'll try to poke around Servo to see if they have any ideas we should steal.

**Comment by TimothyGu** [comment]
Interesting, I did not think about `undefined` when considering these cases. I think, though, that there is a slight confusion in what I want to do: for those nonconformant cases like calling `a.foo(undefined)` where `a` is an instance of 

```webidl
interface A {
  void foo();
  void foo(Node? arg);
}
```

I intended these more delicate handling to be done in the implementation code (i.e. prose), rather than not at all. The idea is then to make webidl2js generate moderately good code that allow a _superset_ of what the IDL actually allows, but have stricter checks done in the implementation class.

That said, I'm not averse to doing some experiments. The part of the overload resolution algorithm that's particularly giving me headache is how the variable _S_ (the [effective overload set](https://heycam.github.io/webidl/#dfn-effective-overload-set)) is used in runtime, while in webidl2js it is only available at compile time. It would be helpful if some sample generated C++ or Rust binding files are provided. It's somewhat difficult for me to read through Servo's [binding code generator](https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py), the entirety of which is contained in one Python file; and I can't say I'm excited to read through Blink's [C++ code generator](https://github.com/mirror/chromium/tree/master/third_party/WebKit/Source/bindings/core/v8) either.

**Comment by bzbarsky** [comment]
> for those nonconformant cases like calling a.foo(undefined) where a is an instance of

In what way is that case "nonconformant"?  Or do you mean "odd, because they treat undefined and missing differently"?

> It would be helpful if some sample generated C++ or Rust binding files are provided.

Sure.  See http://searchfox.org/mozilla-central/rev/d3307f19d5dac31d7d36fc206b00b686de82eee4/dom/bindings/test/TestCodeGen.webidl for some test IDL (search for "overload" to find some tests).  The corresponding generated code is http://searchfox.org/mozilla-central/source/__GENERATED__/dom/bindings/TestCodeGenBinding.cpp (warning: 56000 or so lines of C++).  In any case, you can search in there for "overload" too.

If you have specific questions about how the generator would handle some set of overloads, it's pretty easy for me to generate those for you, fwiw.

**Comment by bzbarsky** [comment]
Oh, and sadly I can't permalink to the generated code, so when you load it you will just get whatever the current thing is that corresponds to the current http://searchfox.org/mozilla-central/source/dom/bindings/test/TestCodeGen.webidl

**Comment by TimothyGu** [comment]
That helps, thanks a lot.

>> for those nonconformant cases like calling `a.foo(undefined)` where `a` is an instance of
>
> In what way is that case "nonconformant"? Or do you mean "odd, because they treat undefined and missing differently"?

Apologies, I misspoke. I meant 

```webidl
void stroke();
void stroke(Path2D path);
```

**Comment by bzbarsky** [comment]
OK, so what checks were you expecting to do in the implementation class in that case?
