### ISSUE TITLE
Unroll argument conversion loop (for non-... args)

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#5]
``` js
  const args = [];
  for (let i = 0; i < arguments.length && i < 3; ++i) {
    args[i] = arguments[i];
  }
  args[0] = conversions["DOMString"](args[0]);
```

could become

``` js
args[0] = conversions["DOMString"](arguments[0]);
args[1] = arguments[1];
args[2] = arguments[2];
```

This also helps with #4 since it automatically fills out `args[2]` with `undefined` if it wasn't passed.

**Comment by Sebmaster** [comment]
I guess this is kinda related to #4. I'm still hanging on to that thought of ensuring arguments.length equivalence for impl classes.

**Comment by domenic** [comment]
I am pretty sure impl classes should not rely on arguments.length though. I don't think WebIDL even allows that checking. It is all handled in the WebIDL layer.

**Comment by Sebmaster** [comment]
In order to fix the dictionary thing, `arguments.length` has been broken already, so we won't need a major for further changes there, but I haven't unrolled the loop yet since we need to do a bit of conditionals there to support variadic args.

**Comment by domenic** [comment]
I notice this kind of happened but there's a tryImplForWrapper loop above the unrolled conversions now. I think we should be able to apply tryImplForWrapper only to (known?) interface types.

**Comment by Sebmaster** [comment]
> I think we should be able to apply tryImplForWrapper only to (known?) interface types.

Not right, now, since we never know about all the interface types. Take Node.dispatchEvent for example. We don't actually know about the Event type there (in jsdom, due to our folder structure at least, since we convert all folders seperately).

I plan to update the conversion interface to include more state so you can add multiple folders to the same conversion process, so we'd know about the whole interface system, but haven't gotten to it yet.

**Comment by TimothyGu** [comment]
An update: since about six months ago we no longer try to get the impl if the type is known not to be an interface (sequences, records, promises, primitives). There is still the major pain point that we don't yet have a way to import types from other modules. E.g. the URL interface is implemented in whatwg-url using webidl2js, but the webidl2js in jsdom doesn't know URL is an interface, and even though it still tries unwrapping it doesn't work because the impl symbol is different for interfaces in another module.

I've got a fix in the works, but will have to change up the type system a bit here so that it doesn't assume the impl symbol is the same for all interfaces. I'll also have to think of a solution for hybrids like Window, in that it functions like a generated class and has impl property (because it inherits EventTarget), but is not actually generated.
