### ISSUE TITLE
Add a USVString reflector

### ISSUE THREAD

**Issue by Zirro** [jsdom/webidl2js#93]
The behaviour of USVString reflection is defined [here](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflecting-content-attributes-in-idl-attributes%3Aidl-usvstring). jsdom currently implements it as a utility function, [reflectURLAttribute()](https://github.com/tmpvar/jsdom/blob/e2ea031fd763cd65dcd152f915f844a9ad74fb5d/lib/jsdom/utils.js#L130), instead of using webidl2js with `[Reflect]`.

While webidl2js would ideally implement this instead, it requires a URL parser which in turn must have access to the Document and any potential `<base>` elements, thus creating a dependency on [whatwg-url](https://github.com/jsdom/whatwg-url) and access to the DOM. These dependencies are probably too far outside the scope of a general purpose Web IDL to JavaScript converter.

However, the README for `[Reflect]` says that:

> In the future we may move this extended attribute out into some sort of plugin, since it is more related to HTML than to Web IDL.

Doing this should allow us to add a USVString reflector without additional weight or complexity in webidl2js itself.

**Comment by TimothyGu** [comment]
The main difficulty with drafting a plugin API is determining the scope of how powerful such an API should be, since in spec there are no limits on how extended attributes operate. While some like `[Reflect]` basically defines the entirety of an attribute getter/setter, many other extended attributes (such as those defined in Web IDL) only affect a portion of the behavior of these getters/setters. How multiple plugins act together (if they be allowed) is also an open question.

In the interim, I'm okay with adding a dependency to whatwg-url (and implicit dependency to jsdom internals) for this specific feature, as we already have very HTML-oriented features already. I'd prefer a separate `[ReflectURL]` extended attribute than the existing `[Reflect]` which is more general purpose, since the definition in HTML for the USVString reflection you are referring to is called "reflecting IDL attribute is a USVString attribute whose content attribute is **defined to contain a URL**", while "If a reflecting IDL attribute is a DOMString or USVString attribute but doesn't fall into any of the above categories, then the getting and setting must be done in a transparent, case-preserving manner."

**Comment by Zirro** [comment]
I agree about using `[ReflectURL]`, and if the rest of the team feels that depending on whatwg-url/the DOM is alright, that's fine with me too.

Having said that, this is now being handled manually in jsdom so we do have time to figure out a plugin API if we want to.
